In [1]:
import numpy as np

**Задание 1**

In [2]:
n = int(input('Введите N='))
np.arange(n-1,-1,-1)

Введите N=6


array([5, 4, 3, 2, 1, 0])

**Задание 2**

In [28]:
n = int(input('Введите N='))

matrix = np.diag(np.arange(n))
matrix[n:0:-1]

sum_diag = np.sum(matrix)

print(f'Матрица:\n{matrix}\nСумма значений на диагонале: {sum_diag}')

Введите N=6
Матрица:
[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]
Сумма значений на диагонале: 15


**Задание 3**

In [3]:
from numpy import linalg

In [4]:
a = np.array([ [4, 2, 1], [1, 3, 0], [0, 5, 4]])

b = np.array([4, 12, -3])

result = linalg.solve(a,b)

print(result)

[ 0.46666667  3.84444444 -5.55555556]


In [31]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

**Задание 4**

In [34]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [61]:
def cosine_similarity(users_stats, next_user_stats):
     list_ = []
     users = []   
     for user_id, stats in enumerate(users_stats):
        aLength = np.linalg.norm(stats)
        bLength = np.linalg.norm(next_user_stats)
        cosine = np.dot( next_user_stats, stats ) / ( aLength * bLength )
        list_.append(cosine)
        users.append(user_id+1)
        similarity = dict(zip(users, list_))
     
     max_val = max(similarity.values())
     for key, value in similarity.items():
        if value == max_val: print(f'Наибольшее соответствие с user_id = {key}, косинусное растояние = {value}.')
            
cosine_similarity(users_stats, next_user_stats)

Наиболшее соответствие с user_id = 8, косинусное растояние = 0.9486832980505138.
